"use client";

import Link from "next/link";
import { ArrowRight, Bot, CheckCircle2, Cpu, Sparkles } from "lucide-react";
import { CREATIVE_TOOLS, MCP_AGENTS, TOP_MODELS } from "@/lib/ai-catalog";

export default function AILabPage() {
  return (
    <div className="p-6 space-y-10 max-w-7xl mx-auto">
      <div><div className="flex items-center gap-2 text-xs text-violet-400 mb-2"><Sparkles className="w-4 h-4" /> Claude MCP workspace</div><h1 className="text-3xl font-bold text-white">AI Lab</h1><p className="text-sm text-zinc-400 mt-2">Agents, creative tools, and model routes connected to your Viewmax workspace.</p></div>
      <section><div className="flex items-center justify-between mb-4"><div><h2 className="text-xl font-semibold text-white">Claude MCP Agents</h2><p className="text-xs text-zinc-500 mt-1">Choose an agent workflow to start a focused production task.</p></div><Bot className="w-5 h-5 text-violet-300" /></div><div className="grid sm:grid-cols-2 lg:grid-cols-5 gap-3">{MCP_AGENTS.map((agent) => <Link key={agent.slug} href={agent.href} className="group rounded-2xl border border-white/10 bg-white/[0.03] p-4 hover:border-violet-400/40 hover:bg-white/[0.06] transition-all"><agent.icon className="w-5 h-5 text-violet-300" /><h3 className="mt-4 font-semibold text-white text-sm">{agent.label}</h3><p className="text-xs text-zinc-500 mt-2 leading-relaxed">{agent.description}</p><ArrowRight className="w-4 h-4 text-zinc-600 mt-4 group-hover:text-violet-300 group-hover:translate-x-1 transition-all" /></Link>)}</div></section>
      <section><div className="mb-4"><h2 className="text-xl font-semibold text-white">Creative Tools</h2><p className="text-xs text-zinc-500 mt-1">Production surfaces already available in this web app.</p></div><div className="grid sm:grid-cols-2 lg:grid-cols-4 gap-4">{CREATIVE_TOOLS.map((tool) => <Link key={tool.label} href={tool.href} className="group rounded-2xl border border-white/10 bg-white/[0.03] p-5 hover:bg-white/[0.06] transition-all"><div className={`w-10 h-10 rounded-xl bg-gradient-to-br ${tool.accent} flex items-center justify-center`}><tool.icon className="w-5 h-5 text-white" /></div><h3 className="mt-5 font-semibold text-white">{tool.label}</h3><p className="text-sm text-zinc-500 mt-2">{tool.description}</p><div className="mt-4 inline-flex items-center gap-1 text-xs text-violet-300">Open tool <ArrowRight className="w-3.5 h-3.5" /></div></Link>)}</div></section>
      <section><div className="mb-4"><h2 className="text-xl font-semibold text-white">Top AI Models</h2><p className="text-xs text-zinc-500 mt-1">Model choices route into the matching Viewmax studio.</p></div><div className="grid sm:grid-cols-2 lg:grid-cols-4 gap-3">{TOP_MODELS.map((model) => <Link key={model.label} href={model.href} className="rounded-2xl border border-white/10 bg-white/[0.03] p-4 hover:border-cyan-400/30 transition-all"><div className="flex items-center justify-between gap-2"><Cpu className="w-5 h-5 text-cyan-300" /><span className="rounded-full bg-white/5 px-2 py-1 text-[10px] text-zinc-400">{model.type}</span></div><h3 className="mt-4 text-sm font-semibold text-white">{model.label}</h3><p className="text-xs text-zinc-500 mt-2 leading-relaxed">{model.description}</p><div className="mt-4 flex items-center gap-1 text-[11px] text-emerald-300"><CheckCircle2 className="w-3.5 h-3.5" /> Available route</div></Link>)}</div></section>
    </div>
  );
}
